import Navbar from "@/app/(main)/components/common/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Footer from "./components/common/Footer";
import ActionButton from "./components/common/ActionButton";
import AuthProvider from "./components/common/AuthProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </head>
      <body className="min-h-full flex flex-col bg-background text-on-background selection:bg-secondary-container" >
        <AuthProvider>
          <Navbar />
          {children}
          <Footer />
          <ActionButton/>
        </AuthProvider>
      </body>
    </html>
  );
}
